---
collections:
  - name: ansible.controller
    version: 4.3.1
  - name: redhat_cop.controller_configuration
    version: 2.1.1
  #linux
  - name: redhat.insights
    version: 1.0.7
  - name: redhat.rhel_system_roles
    version: 1.16.2
  - name: community.general
    version: 5.8.5
  - containers.podman
  #windows
  - chocolatey.chocolatey
  - name: community.windows
    version: 1.10.0
  - name: ansible.windows
    version: 1.9.0
  #cloud
  - name: azure.azcollection
    version: 1.13.0
  - name: amazon.aws
    version: 3.1.1
  #satellite
  - name: redhat.satellite
    version: 3.3.0
  #network
  - name: cisco.ios
    version: 3.1.0
  - name: cisco.nxos
    version: 3.0.0
  - name: cisco.iosxr
    version: 3.0.0
