---
- name: Arbitrary PowerShell
  hosts: "{{ HOSTS | default('windows') }}"
  gather_facts: false

  tasks:
  - name: Return a failure back to Ansible
    ansible.windows.win_powershell:
    script: | 
      (Invoke-RestMethod -Method 'GET' -Uri 'https://catfact.ninja/fact').fact
    register: cat_fact

  - debug:
      var: cat_fact
