---
- hosts: localhost
  gather_facts: no
  vars_files:
    - "{{demo}}/setup.yml"
  vars:
    controller_validate_certs: false

  tasks:
    - name: All demos vars
      include_vars:
        file: "all/setup.yml"
        name: all_systems

    - name: Setup Components
      include_role:
        name: "redhat_cop.controller_configuration.{{ item }}"
      loop: "{{ all_systems.controller_components }}"
      when:
        - controller_components | d("") | length > 0

    - name: Print Message
      debug:
        msg: "{{ user_message }}"
      when: user_message is defined