---
- name: Include platform variables
  ansible.builtin.include_vars:
    file: "rhel{{ ansible_distribution_major_version }}.yml"

- name: Install SCAP dependencies
  ansible.builtin.package:
    name:
      - scap-security-guide
      - openscap
      - openscap-scanner
    state: present

- name: Run SCAP scan
  ansible.builtin.command: "oscap xccdf eval --profile {{ _scap_profile }} --report /tmp/scap_report.html {{ scap_content }}"
  args:
    chdir: /tmp
