file_path: /var/www/html
vendor:
  ios: &my_value 'Cisco'
  nxos: *my_value
  iosxr: *my_value
  junos: "Juniper"
  eos: "Arista"
transport:
  cliconf: "Network_CLI"
  netconf: "NETCONF"
  nxapi: "NX-API"