---
- hosts: "{{ HOSTS }}"
  become: yes
  vars:
    # env: undef
    satellite_url: "{{ lookup('ansible.builtin.env', 'SATELLITE_SERVER') }}"
  roles:
    - demo.satellite.register_host
    - redhat.rhel_system_roles.cockpit
