- name: create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/network.html"

- name: copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true

- name: copy logos over
  ansible.builtin.copy:
    src: "{{ item }}" 
    dest: "{{ file_path }}"
    directory_mode: true
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"

- name: Display link to Linux patch report
  ansible.builtin.debug:
    msg: "Please go to http://{{ hostvars[report_server]['ansible_host'] }}/reports/network.html"