---
- hosts: "{{ HOSTS }}"
  become: yes
  vars:
    report_server: node1
  
  tasks:
  - include_role:
      name: demo.patching.patch_linux

  - name: Tell user when Insights is not configured
    debug:
      msg: "Insights client does not appear to be configured. Scan will be skipped"
    when:
      - ansible_local.insights.system_id is not defined

  - name: Run the Insights Client Scan
    command: insights-client
    when:
      - not ansible_check_mode
      - ansible_local.insights.system_id is defined

  - block:

    - include_role:
        name: "{{ item }}"
      loop:
        - demo.patching.report_server
        - demo.patching.report_linux
        - demo.patching.report_linux_patching

    - include_role:
        name: demo.patching.report_server
        tasks_from: linux_landing_page
        
    delegate_to: "{{ report_server }}"
    run_once: yes
