---
- name: Run Shell Script
  hosts: "{{ HOSTS }}"
  become: yes
  gather_facts: no
  vars:
    shell_script: undef

  tasks:
    - name: Run Shell Script
      shell: "{{ shell_script }}"
      register: shell_output

    - name: Print script output
      debug:
        var: shell_output.stdout_lines

    - debug:
        msg: You should really consider converting this script to a playbook!
      run_once: yes
