---
- name: OpenSCAP compliance scan
  hosts: "{{ _hosts }}"
  become: true
  vars:
    report_server: node1

  tasks:
  - name: Run OpenSCAP scan
    ansible.builtin.include_role:
      name: demo.compliance.scap_scan

  - name: Fetch SCAP report
    ansible.builtin.fetch:
      src: /tmp/{{ inventory_hostname }}_scap_report.html
      dest: /tmp

  - block:
    - name: Install report server
      include_role:
        name: demo.patching.report_server

    - name: Find SCAP reports
      ansible.builtin.find:
        paths: /tmp
        patterns: "*.html" 
        recurse: true
      register: scap_reports
      delegate_to: localhost
      run_once: true

    - name: Copy SCAP reports
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "/var/www/html/reports/{{ item.path.split('/')[-1] }}"
      loop: "{{ scap_reports.files }}"

    - name: Update landing page
      include_role:
        name: demo.patching.report_server
        tasks_from: linux_landing_page

    delegate_to: "{{ report_server }}"
    run_once: true
